// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqmshwkwdhslipzkwwvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbXNod2t3ZGhzbGlwemt3d3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODE1NTEsImV4cCI6MjA2NzA1NzU1MX0.5XkLWNNZ6foBvSRZ7Ac1jN8JqZdr_6uzkvQeFCiG7GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});